# Generated by Django 5.0.3 on 2024-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='car2.jpg', upload_to='uploads/'),
        ),
    ]
